name: psikoz
description: Physcology Social Media.
publish_to: 'none'
version: 1.8.0+2

environment:
  sdk: '>=2.18.0 <3.0.0'


dependencies:
  flutter:
    sdk: flutter

    
  
  intl: ^0.17.0
  uuid: ^3.0.6
  
  image_picker: ^0.8.5+3
  image_cropper: ^3.0.0
  flutter_svg: ^1.1.3
  #image
  get: ^4.6.5
  provider: ^6.0.4
  flutter_bloc: ^8.1.1
  #stateManagment
  google_fonts: ^3.0.1
  #font
  ###############

  #HTTP 
  dio: ^5.1.1
  #Json Processing
  json_serializable: ^6.5.4
  json_annotation: ^4.7.0
  build_runner: ^2.3.2
  #Localization vs eklicem


  #Cache
  hive_flutter: ^1.1.0
  hive: ^2.2.3

  
  cupertino_icons: ^1.0.2
  rxdart: ^0.27.6
  lottie: ^2.0.0
  card_swiper: ^2.0.4
  get_storage: ^2.0.3
  file_picker: ^5.2.4
  flutter_colorpicker: ^1.0.3
  shimmer: ^2.0.0
  flutter_datetime_picker: ^1.5.1
  audio_waveforms: ^1.0.1
  path_provider: ^2.0.11
 

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^2.0.0
  hive_generator: ^2.0.0
  flutter_launcher_icons: "^0.11.0"
  flutter_native_splash: ^2.2.16
  liquid_pull_to_refresh: ^3.0.1
  pull_to_refresh: ^2.0.0
  painter: ^2.0.0



flutter_native_splash:
  color : "#000000"
  image : "assets/images/logo.png"
  android : true
  ios : true

flutter_icons:
  image_path: "assets/images/logo.png"
  
  min_sdk_android: 18 # android min sdk min:16, default 21
  android: true
  ios: true
  


flutter:

  
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/images/
   - assets/Icon/
   - assets/lotties/
   - assets/emotion/

  
