// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjVuizr_tb5lXm6kFW9Ui945pa654sYCg',
    appId: '1:308845910376:android:ccfaba4f1a8c75b1285edd',
    messagingSenderId: '308845910376',
    projectId: 'psikoz-teknofest',
    databaseURL: 'https://psikoz-teknofest-default-rtdb.firebaseio.com',
    storageBucket: 'psikoz-teknofest.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfFD0DDxdcXLFloMvsCds2anD4E6iISeI',
    appId: '1:308845910376:ios:2ad5458eb3a420d4285edd',
    messagingSenderId: '308845910376',
    projectId: 'psikoz-teknofest',
    databaseURL: 'https://psikoz-teknofest-default-rtdb.firebaseio.com',
    storageBucket: 'psikoz-teknofest.appspot.com',
    iosClientId: '308845910376-k7st00uuj1mb7m5dkjl4qog6o2fn1ipf.apps.googleusercontent.com',
    iosBundleId: 'com.bexbow.psikoz',
  );
}
